public enum Symbol {
  ERROR, EOF,
  PLUS, MINUS, TIMES, DIV,
  OPEN_PAR, CLOSE_PAR, OPEN_BRACE, CLOSE_BRACE,
  COMMA, SEMICOLON, ASSIGN,
  INT, MAIN, PRINT, READ, VOID,
  IF, ELSE, WHILE,
  NUMBER, IDENT
}
